name: "Build & Test"

on:
  push:
    branches: [ "main", "docs-ci" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup_and_build:
    name: Setup 
    runs-on: ubuntu-latest

    steps:
      - name: Enviroinment Check 
        run: env

      - name: Installing make & other tools
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Fetching source code
        uses: actions/checkout@v4

      - name: Build
        run: |
          make